/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xyz;

/**
 *
 * @author SONALI
 */
public class NewJFrame extends javax.swing.JFrame {
String[] currencyUnits={
"Unit",
"ArgentinePeso",
"AustralianDollar",
"BahrainiDinar",
"BotswanaPula",
"BrazilianReal",
"BruneianDollar",
"BulgarianLev",
"CanadianDollar",
"ChileanPeso",
"ChineseYuanRenminbi",
"ColombianPeso",
"CroatianKuna",
"CzechKoruna",
"DanishKrone",
"EmiratiDirham",
"Euro",
"HongKongDollar",
"HungarianForint",
"IcelandicKrona",
"IndianRupee",
"IndonesianRupiah",
"IranianRial",
"IsraeliShekel",
"JapaneseYen",
"KazakhstaniTenge",
"KuwaitiDinar",
"LibyanDinar",
"MalaysianRinggit",
"MauritianRupee",
"MexicanPeso",
"NepaleseRupee",
"NewZealandDollar",
"NorwegianKrone",
"OmaniRial",
"PakistaniRupee",
"PhilippinePeso",
"PolishZloty",
"QatariRiyal",
"RomanianNewLeu",
"RussianRuble",
"SaudiArabianRiyal",
"SingaporeDollar",
"SouthAfricanRand",
"SouthKoreanWon",
"SriLankanRupee",
"SwedishKrona",
"SwissFranc",
"TaiwanNewDollar",
"ThaiBaht",
"TrinidadianDollar",
"TurkishLira",
"USDollar",
"VenezuelanBolivar"};

String[] pounds={
    "0.00",
    "86.120723",
"1.806644",
"0.464296",
"14.259915",
"6.540806",
"1.725649",
"2.160493",
"1.680254",
"1009.145641",
"8.731452",
"4628.134914",
"8.361277",
"29.450061",
"8.237757",
"4.534912",
"1.104643",
"9.570406",
"382.214307",
"170.651787",
"94.200278",
"17591.833925",
"51894.224488",
"4.26267",
"131.961681",
"497.728426",
"0.381072",
"1.728515",
"5.27003",
"49.825549",
"27.958304",
"151.426946",
"1.926994",
"11.906868",
"0.474792",
"205.938358",
"61.834179",
"4.931156",
"4.49478",
"5.346473",
"85.776592",
"4.630611",
"1.725649",
"21.391454",
"1496.802936",
"228.526922",
"11.701151",
"1.176005",
"36.590667",
"38.311378",
"8.366633",
"8.46114",
"1.23483",
"12.332861",
};
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstC = new javax.swing.JComboBox<>();
        secondC = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        fisrtCUnit = new javax.swing.JLabel();
        secondCUnit = new javax.swing.JLabel();
        convertC = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Currency Converter");

        jLabel2.setText("To Currency of");

        jLabel3.setText("From Currency of");

        firstC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose One...", "Argentine", "Australia", "Bahrain", "Botswana", "Brazil", "Brunei", "Bulgari", "Canada", "Chili", "China", "Colombia", "Croatian", "Czech", "Danish", "Emirati", "Europe", "HongKong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Israel", "Japan", "Kazakhstan", "Kuwait", "Libya", "Malaysia", "Mauriti", "Mexico", "Nepal", "NewZealand", "Norwegia", "Oman", "Pakistan", "Philippine", "Polish", "Qatar", "Romania", "Russia", "SaudiArabia", "Singapore", "SouthAfrica", "SouthKorea", "Sri Lanka", "Swedish", "Swiss", "Taiwan", "Thai", "Trinidadia", "Turk", "US", "Venezuela" }));
        firstC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                firstCItemStateChanged(evt);
            }
        });

        secondC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one..", "Argentine", "Australia", "Bahrain", "Botswana", "Brazil", "Brunei", "Bulgari", "Canada", "Chili", "China", "Colombia", "Croatian", "Czech", "Danish", "Emirati", "Europe", "HongKong", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Israel", "Japan", "Kazakhstan", "Kuwait", "Libya", "Malaysia", "Mauriti", "Mexico", "Nepal", "NewZealand", "Norwegia", "Oman", "Pakistan", "Philippine", "Polish", "Qatar", "Romania", "Russia", "SaudiArabia", "Singapore", "SouthAfrica", "SouthKorea", "Sri Lanka", "Swedish", "Swiss", "Taiwan", "Thai", "Trinidadia", "Turk", "US", "Venezuela" }));
        secondC.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                secondCItemStateChanged(evt);
            }
        });

        t1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        t2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        fisrtCUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        secondCUnit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        convertC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        convertC.setText("Convert Currency");
        convertC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertCActionPerformed(evt);
            }
        });

        reset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(convertC, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstC, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1)
                            .addComponent(fisrtCUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(secondCUnit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(secondC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(secondC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fisrtCUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondCUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(convertC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_firstCItemStateChanged
       int index=firstC.getSelectedIndex();
        fisrtCUnit.setText(currencyUnits[index]);
    }//GEN-LAST:event_firstCItemStateChanged

    private void secondCItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_secondCItemStateChanged
       int index=secondC.getSelectedIndex();
        secondCUnit.setText(currencyUnits[index]);
    }//GEN-LAST:event_secondCItemStateChanged

    private void convertCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertCActionPerformed
        double amountToChange=Double.parseDouble(t1.getText());
        double amountInPound=0.0;
        int index=firstC.getSelectedIndex();
        amountInPound = amountToChange/Double.parseDouble(pounds[index]);

        double amountChanged=0.0;
        int indexb=secondC.getSelectedIndex();
        amountChanged=amountInPound * Double.parseDouble(pounds[indexb]);
        String value=String.format("%.2f",amountChanged);
        t2.setText(value);
       
    }//GEN-LAST:event_convertCActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       firstC.setSelectedIndex(0);
       secondC.setSelectedIndex(0);
       t1.setText("");
       t2.setText("");
       
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertC;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> firstC;
    private javax.swing.JLabel fisrtCUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reset;
    private javax.swing.JComboBox<String> secondC;
    private javax.swing.JLabel secondCUnit;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    // End of variables declaration//GEN-END:variables
}
